// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.ksn.worker.ice.printer;

public interface PrinterIce extends Ice.Object,
                                    _PrinterIceOperations, _PrinterIceOperationsNC
{
    public static final String ice_staticId = "::com::ksn::worker::ice::printer::PrinterIce";

    public static final long serialVersionUID = 2294823612882036668L;
}
